FROM node:23.4-bullseye-slim 

RUN npm install -g pnpm 

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install 

COPY . .

ENTRYPOINT [ "./run-prod.sh" ]

EXPOSE 3000

CMD ["pnpm", "start"]
